version: '3'

services:
  krypton:
    image: aidanbennett/krypton-demo:latest
    container_name: krypton
    ports:
      - "25565:25565"
    # environment:
    #   - EULA=TRUE
    volumes:
      - ./config:/opt/krypton/config
      - ./world:/opt/krypton/world
      - ./plugins:/opt/krypton/plugins
      - ./logs:/opt/krypton/logs/
